routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FolderController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\StepController;
use GuzzleHttp\Middleware;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);

Route::group(['middleware' => 'verified'], function () {
    Route::resource('client', ClientController::class);
    Route::resource('project', ProjectController::class);
    Route::post('project/invoice/{id}', [ProjectController::class, 'payment'])->name('project.invoice');
});
Route::get('/', DashboardController::class)->middleware(['CheckRole:alluser', 'auth']);

Route::get('/admin', [AdminController::class, 'index'])->middleware(['CheckRole:admin']);


// route::prefix('project')

// Route::resource('step', StepController::class);

Route::post('folder/{project}', [FolderController::class, 'store'])->name('folder.store');


Route::put('store/{project}', [StepController::class, 'store'])->name('step.simpan');

Route::post('step/{id}', [StepController::class, 'finished'])->name('step.finished');

Route::get('project/{project}', [ProjectController::class, 'projectstep'])->name('project.step');

Route::post('folder/save/{project}', [FolderController::class, 'store'])->name('folder.save');

// Route::resource('folder', FolderController::class);

Route::resource('step', StepController::class);

Route::delete('/user/{user}', [AdminController::class, 'destroy'])->name('user.destroy');

Route::get('/search', SearchController::class)->name('search');

Route::get('tabelproject', function () {
    return view('admin.project');
})->name('tabelproject');

Route::get('tabeluser', function () {
    return view('admin.user');
})->name('tabeluser');

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    use HasFactory;

    protected $fillable = ['nama_project', 'deskripsi', 'harga', 'deadline', 'client_id', 'user_id'];


    public function client()
    {
        return $this->belongsTo(Client::class);
    }

    public function payment()
    {
        return $this->hasOne(Payment::class);
    }

    public function steps()
    {
        return $this->hasMany(Step::class);
    }
    public function folder()
    {
        return $this->hasOne(Folder::class);
    }

    public function users()
    {
        return $this->belongsToMany(User::class);
    }
    
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Mail\DataProject;
use App\Models\Client;
use App\Models\Project;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Mail;

use function PHPUnit\Framework\returnSelf;

class ProjectController extends Controller
{

    public function index()
    {
        $project = Auth::user()->projects;
        return view('project.index', ['project' => $project]);
    }

    public function store(Request $request)
    {
        $data = $request->validate([
            'nama_project' => 'required',
            'client_id' => 'required',
            'deskripsi' => 'required',
            'harga' => ['required', 'integer'],
            'deadline' => 'required',
        ]);
        $data['users'] = $request->users;
        $data['user_id'] = Auth::user()->id;
        $project = Project::create($data);
        $project->users()->sync($request->users);
        return back()->withStatus('Data Sudah Tersimpan');
    }

    public function show(Project $project)
    {
        $steps = $project->steps;
        $folder = $project->folder;
        return view('project.show', compact('steps', 'project', 'folder'));
    }

    public function edit(Project $project)
    {

        $clients = Client::get();
        $users = User::get();

        return view('project.edit', [
            'project' => $project,
            'clients' => $clients,
            'users' => $users
        ]);
    }

    public function update(Request $request, Project $project)
    {

        $data = $request->validate([
            'nama_project' => 'required',
            'client_id' => 'required',
            'deskripsi' => 'required',
            'harga' => ['required', 'integer'],
            'deadline' => 'required',
        ]);
        $project->update($data);
        $project->users()->sync($request->users);

        return redirect('admin')->withStatus('Data Berhasil Diupdate');
    }

    public function projectStep(Project $project)
    {


        $steps = $project->steps;

        return view('project.projectstep', [
            'project' => $project,
            'steps' => $steps
        ]);
    }
    public function destroy(Project $project)
    {

        $project->delete();
        return back();
    }

    public function midtransGateway($produk)
    {
        // dd($produk);
        $params = [
            "enabled_payments" => [
                "credit_card", "cimb_clicks", "bca_klikbca", "bca_klikpay", "bri_epay", "echannel",
                "permata_va", "bca_va", "bni_va", "bri_va", "other_va", "gopay", "indomaret",
                "danamon_online", "akulaku", "shopeepay", "uob_ezpay"
            ],

            "transaction_details" => [
                "order_id" => 'order_id-'.$produk->id,
                "gross_amount" => $produk->harga
            ],

            "item_details" => [
                'id' => $produk->id,
                'price' => $produk->harga,
                'quantity' => 1,
                'name' => $produk->nama_project
            ],
            "customer_details" => $produk->client_id,

            "expiry" => [
                "start_time" =>  now()->format('Y-m-d H:i:s T'),
                "unit" => "days",
                "duration" => 1
            ],
        ];
        $url = 'https://app.sandbox.midtrans.com/snap/v1/transactions';

        $headers = [
            "Authorization" => "Basic " . base64_encode(config('payment.server_key')),
            "Accept" => "application/json",
            "Content-Type" =>  "application/json",
        ];
        $respon = Http::withHeaders($headers)->post($url, $params);
        return $respon;
    }

    public function payment(Project $project, $id, Request $request)
    {
        $data = $project->find($id);
        $hai = $this->midtransGateway($data);

        // $hai = $this->midtransGateway($data->id, $data->harga, $data->client_id);
        return $this->SendMail($data, $hai);
    }

    public function SendMail($project, $respon)
    {
        // complete
        $data = json_decode($respon, true);
        $client = $project->client;
        // dd($client);
        Mail::to($client->email)->send(new DataProject($data));
        return back();
    }
}

app/Http/Livewire/ProjectTable.php
<?php

namespace App\Http\Livewire;

use App\Models\Project;
use Illuminate\Support\Carbon;
use Illuminate\Database\QueryException;
use Illuminate\Database\Eloquent\Builder;
use PowerComponents\LivewirePowerGrid\Button;
use PowerComponents\LivewirePowerGrid\Column;
use PowerComponents\LivewirePowerGrid\PowerGrid;
use PowerComponents\LivewirePowerGrid\PowerGridEloquent;
use PowerComponents\LivewirePowerGrid\PowerGridComponent;
use PowerComponents\LivewirePowerGrid\Traits\ActionButton;
use PowerComponents\LivewirePowerGrid\Rules\Rule;

final class ProjectTable extends PowerGridComponent
{
    use ActionButton;

    //Messages informing success/error data is updated.
    public bool $showUpdateMessages = true;


    public function header(): array
    {
        return [
            Button::add('bulk-sold-out')
                ->caption(__('Mark as Sold-out'))
                ->class('cursor-pointer block bg-indigo-500 text-white')
                ->emit('bulkSoldOutEvent', [])
        ];
    }

    /*
    |--------------------------------------------------------------------------
    |  Features Setup
    |--------------------------------------------------------------------------
    | Setup Table's general features
    |
    */
    public function setUp(): void
    {
        $this->showCheckBox()
            ->showPerPage()
            ->showSearchInput()
            ->showExportOption('download', ['excel', 'csv']);
    }

    /*
    |--------------------------------------------------------------------------
    |  Datasource
    |--------------------------------------------------------------------------
    | Provides data to your Table using a Model or Collection
    |
    */

    /**
     * PowerGrid datasource.
     *
     * @return  \Illuminate\Database\Eloquent\Builder<\App\Models\Project>|null
     */
    public function datasource(): ?Builder
    {
        return Project::query();
    }

    /*
    |--------------------------------------------------------------------------
    |  Relationship Search
    |--------------------------------------------------------------------------
    | Configure here relationships to be used by the Search and Table Filters.
    |
    */

    /**
     * Relationship search.
     *
     * @return array<string, array<int, string>>
     */
    public function relationSearch(): array
    {
        return [];
    }

    /*
    |--------------------------------------------------------------------------
    |  Add Column
    |--------------------------------------------------------------------------
    | Make Datasource fields available to be used as columns.
    | You can pass a closure to transform/modify the data.
    |
    */
    public function addColumns(): ?PowerGridEloquent
    {
        return PowerGrid::eloquent()
            ->addColumn('id')
            ->addColumn('nama_project')
            ->addColumn('deskripsi')
            ->addColumn('harga')
            ->addColumn('deadline_formatted', function (Project $model) {
                return Carbon::parse($model->deadline)->format('d/m/Y');
            })
            ->addColumn('client_id')
            ->addColumn('created_at_formatted', function (Project $model) {
                return Carbon::parse($model->created_at)->format('d/m/Y H:i:s');
            })
            ->addColumn('updated_at_formatted', function (Project $model) {
                return Carbon::parse($model->updated_at)->format('d/m/Y H:i:s');
            });
    }

    /*
    |--------------------------------------------------------------------------
    |  Include Columns
    |--------------------------------------------------------------------------
    | Include the columns added columns, making them visible on the Table.
    | Each column can be configured with properties, filters, actions...
    |
    */

    /**
     * PowerGrid Columns.
     *
     * @return array<int, Column>
     */
    public function columns(): array
    {
        return [
            Column::add()
                ->title('ID')
                ->field('id')
                ->makeInputRange(),

            Column::add()
                ->title('NAMA PROJECT')
                ->field('nama_project')
                ->sortable()
                ->searchable()
                ->makeInputText(),

            Column::add()
                ->title('DESKRIPSI')
                ->field('deskripsi')
                ->sortable()
                ->searchable(),

            Column::add()
                ->title('HARGA')
                ->field('harga')
                ->makeInputRange(),

            Column::add()
                ->title('DEADLINE')
                ->field('deadline_formatted', 'deadline')
                ->searchable()
                ->sortable()
                ->makeInputDatePicker('deadline'),

            Column::add()
                ->title('CLIENT ID')
                ->field('client_id')
                ->makeInputRange(),

            Column::add()
                ->title('CREATED AT')
                ->field('created_at_formatted', 'created_at')
                ->searchable()
                ->sortable()
                ->makeInputDatePicker('created_at'),

            Column::add()
                ->title('UPDATED AT')
                ->field('updated_at_formatted', 'updated_at')
                ->searchable()
                ->sortable()
                ->makeInputDatePicker('updated_at'),

        ];
    }

    /*
    |--------------------------------------------------------------------------
    | Actions Method
    |--------------------------------------------------------------------------
    | Enable the method below only if the Routes below are defined in your app.
    |
    */

    /**
     * PowerGrid Project Action Buttons.
     *
     * @return array<int, \PowerComponents\LivewirePowerGrid\Button>
     */


    public function actions(): array
    {
        return [
            // Button::add('edit')
            //     ->caption('Edit')
            //     ->class('btn btn-outline-primary')
            //     ->route('project.edit', ['project' => 'id']),

            Button::add('destroy')
                ->caption('Delete')
                ->class('btn btn-outline-primary')
                ->route('project.destroy', ['project' => 'id'])
                ->method('delete')
        ];
    }


    /*
    |--------------------------------------------------------------------------
    | Actions Rules
    |--------------------------------------------------------------------------
    | Enable the method below to configure Rules for your Table and Action Buttons.
    |
    */

    /**
     * PowerGrid Project Action Rules.
     *
     * @return array<int, \PowerComponents\LivewirePowerGrid\Rules\RuleActions>
     */

    /*
    public function actionRules(): array
    {
       return [
           
           //Hide button edit for ID 1
            Rule::button('edit')
                ->when(fn($project) => $project->id === 1)
                ->hide(),
        ];
    }
    */

    /*
    |--------------------------------------------------------------------------
    | Edit Method
    |--------------------------------------------------------------------------
    | Enable the method below to use editOnClick() or toggleable() methods.
    | Data must be validated and treated (see "Update Data" in PowerGrid doc).
    |
    */

    /**
     * PowerGrid Project Update.
     *
     * @param array<string,string> $data
     */

    /*
    public function update(array $data ): bool
    {
       try {
           $updated = Project::query()->findOrFail($data['id'])
                ->update([
                    $data['field'] => $data['value'],
                ]);
       } catch (QueryException $exception) {
           $updated = false;
       }
       return $updated;
    }

    public function updateMessages(string $status = 'error', string $field = '_default_message'): string
    {
        $updateMessages = [
            'success'   => [
                '_default_message' => __('Data has been updated successfully!'),
                //'custom_field'   => __('Custom Field updated successfully!'),
            ],
            'error' => [
                '_default_message' => __('Error updating the data.'),
                //'custom_field'   => __('Error updating custom field.'),
            ]
        ];

        $message = ($updateMessages[$status][$field] ?? $updateMessages[$status]['_default_message']);

        return (is_string($message)) ? $message : 'Error!';
    }
    */
}

resources/views/project/edit.blade.php
@extends('layouts.auth')

@section( 'content')
<div class="row">
    {{-- start profile step --}}

    <div class="col-12 col-lg-4">
        <x-showproject>
            @slot('nama_project')
            {{ $project->nama_project }}
            @endslot
            @slot('harga')
            {{ $project->harga }}
            @endslot
            @slot('deadline')
            {{ $project->deadline }}
            @endslot
        </x-showproject>

        {{-- start kolom edit --}}
        <div class="card mt-3">
            <form action="{{route('folder.store', $project)}}" method="post">
                @csrf

                <div class="modal-body">
                    <div class="mb-3">
                        <label class="form-label">Masukkan Link</label>
                        <input type="text" class="form-control" name="deskripsi"  placeholder="Nama Project">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary ms-auto">
                        UPDATE
                    </button>
                </div>
            </form>
        </div>
        {{-- start kolom edit --}}
    </div>
    {{-- end profile project  --}}

    {{-- start kolom edit --}}
    <div class="col-12 col-lg-8">
        <div class="card">
            <form action="{{route('project.update', $project)}}" method="post">
                @csrf
                @method('put')
                <div class="modal-body">
                    <div class="mb-3">
                        <label class="form-label">Nama Project</label>
                        <input type="text" class="form-control" name="nama_project" value="{{ $project->nama_project }}" placeholder="Nama Project">
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="mb-3">
                                <div class="form-label">Nama Pekerja</div>
                                <select class="form-select select" name="users[]" multiple>
                                    @foreach($users as $user)
                                    <option {{ $project->users()->find($user->id) ? 'selected' : '' }} value="{{ $user->id }}">{{ $user->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="mb-3">
                                <div class="form-label">Nama Pekerja</div>
                                <select class="form-select select" name="client_id">
                                    <option value=""> -- Pilih Client -- </option>
                                    @foreach($clients as $client)
                                    <option {{ $client->id == $project->client->id ? 'selected' : ' ' }} value="{{ $client->id }}">{{ $client->nama_client }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="mb-3">
                                <label class="form-label">Harga</label>
                                <input type="text" name="harga" value="{{ $project->harga }}" class="form-control">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="mb-3">
                                <label class="form-label">Deadline</label>
                                <input type="date" name="deadline" value="{{ $project->deadline }}" class="form-control">
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div>
                                <label class="form-label">Deskripsi</label>
                                <textarea name="deskripsi" class="form-control" rows="3"> {{ $project->deskripsi }}</textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary ms-auto">
                        UPDATE
                    </button>
                </div>
            </form>
        </div>
    </div>
    {{-- start kolom edit --}}

</div>
@endsection

resources/views/project/index.blade.php
@extends('layouts.auth')
@section('content')

<div class="container">

    <div class="page-header">
        <h1 class="page-title">
            {{-- --}}
        </h1>
    </div>

    {{-- <livewire:project-table/> --}}

    <div class="">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">pros</h3>
            </div>
            <div class="table-responsive">
                <table class="table card-table table-vcenter text-nowrap">
                    <thead>
                        <tr>
                            <th class="w-1">No.</th>
                            <th>Lnagkah</th>
                            <th>Catatan</th>
                            <th>Created</th>
                            <th>Status</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach($project as $angka => $pro)

                        <tr>
                            <td><span class="text-muted">{{ 1 + $angka++ }}</span></td>
                            <td><a href="invoice.html" class="text-inherit">{{ $pro->nama_project }}</a></td>
                            <td>

                            </td>
                            <td>
                                15 Dec 2017
                            </td>
                            {{-- <td>
                                <span class="status-icon bg-success"></span> Paid
                            </td> --}}
                            <td class="text-right row">

                                <form action="{{route('project.destroy', $pro)}}" method="post">
                                    @csrf
                                    @method('delete')
                                    <button type="submit" class="dropdown-item btn btn-sm btn-outline-primary">
                                        <i class="dropdown-icon fe fe-trash"></i>Delete
                                    </button>
                                    {{-- <li class="dropdown-item"><i class="dropdown-icon fe fe-trash"></i> Delete </li> --}}
                                </form>

                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/project/projectstep.blade.php
@extends('layouts.auth')

@section('content')

<div class="row">
    {{-- start profile step --}}

    <div class="col-12 col-lg-4">
        <x-showproject>
            @slot('nama_project')
            {{ $project->nama_project }}
            @endslot
            @slot('harga')
            {{ $project->harga }}
            @endslot
            @slot('deadline')
            {{ $project->deadline }}
            @endslot
        </x-showproject>
    </div>
    {{-- end profile project  --}}


    <div class="col-12 col-lg-6">
        <div class="card">
            <div class="table-responsive">
                <table class="table table-vcenter card-table">
                    <thead>
                        <tr>
                            <th>Name Langkah</th>
                            <th>Hapus</th>
                            <th>Status</th>
                            <th>Edit</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($steps as $step)
                        <tr>
                            <td>{{$step->nama_langkah}}</td>
                            <td>
                                <form action="{{route('step.destroy', $step)}}" method="post">
                                    @csrf
                                    @method('delete')
                                    <button class="btn" type="submit">Hapus</button>
                                </form>
                            </td>
                            <td>
                                <form action="{{route('step.finished', $step)}}" method="post">
                                    @csrf
                                    <button class="btn" type="submit">{{($step->finished == 'Y') ? 'Selesai' : 'Belum' }}</button>
                                </form>
                            </td>
                            <td>
                                <a class="btn" data-bs-toggle="modal" data-bs-target="#step{{$step->id}}">
                                    Edit
                                </a>
                                <div class="modal modal-blur fade" id="step{{$step->id}}" role="dialog" aria-hidden="true">
                                    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title">Langkah</h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                            </div>
                                            <form action="{{route('step.update', $step)}}" method="post">
                                                @csrf
                                                @method('put')
                                                <div class="modal-body row">
                                                    <div class="mb-3 col-6">
                                                        <label class="form-label">Nama Langkah</label>
                                                        <input type="text" class="form-control" name="nama_langkah" value="{{$step->nama_langkah}}" placeholder="Nama Project">
                                                    </div>
                                                </div>
                                                <div class="modal-footer">
                                                    <a href="#" class="btn btn-link link-secondary" data-bs-dismiss="modal">
                                                        close modal
                                                    </a>
                                                    <button type="submit" class="btn btn-primary ms-auto">
                                                        + Buat
                                                    </button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </td>

                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>







@endsection