routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FolderController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\StepController;
use GuzzleHttp\Middleware;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);

Route::group(['middleware' => 'verified'], function () {
    Route::resource('client', ClientController::class);
    Route::resource('project', ProjectController::class);
    Route::post('project/invoice/{id}', [ProjectController::class, 'payment'])->name('project.invoice');
});
Route::get('/', DashboardController::class)->middleware(['CheckRole:alluser', 'auth']);

Route::get('/admin', [AdminController::class, 'index'])->middleware(['CheckRole:admin']);


// route::prefix('project')

// Route::resource('step', StepController::class);

Route::post('folder/{project}', [FolderController::class, 'store'])->name('folder.store');


Route::put('store/{project}', [StepController::class, 'store'])->name('step.simpan');

Route::post('step/{id}', [StepController::class, 'finished'])->name('step.finished');

Route::get('project/{project}', [ProjectController::class, 'projectstep'])->name('project.step');

Route::post('folder/save/{project}', [FolderController::class, 'store'])->name('folder.save');

// Route::resource('folder', FolderController::class);

Route::resource('step', StepController::class);

Route::delete('/user/{user}', [AdminController::class, 'destroy'])->name('user.destroy');

Route::get('/search', SearchController::class)->name('search');

Route::get('tabelproject', function () {
    return view('admin.project');
})->name('tabelproject');

Route::get('tabeluser', function () {
    return view('admin.user');
})->name('tabeluser');

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    use HasFactory;

    protected $fillable = ['nama_client', 'email', 'no_wa',];

    public function Projects()
    {
        return $this->hasMany(Project::class);
    }
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Models\Client;
use App\Models\Project;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ClientController extends Controller
{

    public function index(Client $client)
    {
        $clients = Client::all();

        return view('client.index', [
            'clients' => $clients,
        ]);
    }

    public function store(Request $request)
    {

        // dd($request->all());
        $data = $request->validate([
            'nama_client' => 'required',
            'email' => 'required',
            'no_wa' => 'required'
        ]);
        Auth::user()->clients()->create($data);

        return back();
    }


    public function show(Client $client)
    {
        $projects = Project::get(['id', 'nama_project', 'harga', 'client_id', 'deadline']);
        return view('client.show', compact('client', 'projects'));
    }

    public function edit(Client $client)
    {
        return view('client.edit', ['client' => $client]);
    }

    public function update(Request $request, Client $client)
    {
        $client->update([
            'nama_client' => $request->nama_client,
            'no_wa' => $request->no_wa,
            'email' => $request->email,
        ]);
        return back();
    }

    public function destroy(Client $client)
    {
        $client->delete();
        return back();
    }
}

resources/views/client/index.blade.php
@extends('layouts.auth')
@section('content')


<div class="my-3 my-md-5">
    <div class="container">
        <div class="row row-cards row-deck">
            <div class="col-12">
                <div class="card">
                    <div class="table-responsive">
                        <table class="table table-hover table-outline table-vcenter text-nowrap card-table">
                            <thead>
                                <tr>
                                    <th class="text-center w-1"><i class="icon-people"></i></th>
                                    <th>User</th>
                                    <th>Usage</th>
                                    <th class="text-center">Payment</th>
                                    <th>Activity</th>
                                    <th class="text-center">Satisfaction</th>
                                    <th class="text-center"><i class="icon-settings"></i></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($clients as $angka => $client)
                                <tr>
                                    <td class="text-center">
                                        <div class="avatar d-block" style="background-image: url(demo/faces/female/26.jpg)">
                                            <span class="avatar-status bg-green"></span>
                                        </div>
                                    </td>
                                    <td>
                                        <div>{{ $client->nama_client }}</div>
                                        <div class="small text-muted">
                                            Registered: Mar 9, 2018
                                        </div>
                                    </td>
                                    <td>
                                        <div class="clearfix">
                                            <div class="float-left">
                                                <strong>42%</strong>
                                            </div>
                                            <div class="float-right">
                                                <small class="text-muted">Jun 11, 2015 - Jul 10, 2015</small>
                                            </div>
                                        </div>
                                        <div class="progress progress-xs">
                                            <div class="progress-bar bg-yellow" role="progressbar" style="width: 42%" aria-valuenow="42" aria-valuemin="0" aria-valuemax="100"></div>
                                        </div>
                                    </td>
                                    <td class="text-center">
                                        <i class="payment payment-visa"></i>
                                    </td>
                                    <td>
                                        <div class="small text-muted">Last login</div>
                                        <div>4 minutes ago</div>
                                    </td>
                                    <td class="text-center">
                                        <div class="mx-auto chart-circle chart-circle-xs" data-value="0.42" data-thickness="3" data-color="blue">
                                            <div class="chart-circle-value">42%</div>
                                        </div>
                                    </td>
                                    <td class="text-center">
                                        <div class="item-action dropdown">
                                            <a href="javascript:void(0)" data-toggle="dropdown" class="icon"><i class="fe fe-more-vertical"></i></a>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                <a href=" {{ route('step.index') }} " class="dropdown-item"><i class="dropdown-icon fe fe-tag"></i> Action </a>
                                                <a href="javascript:void(0)" class="dropdown-item"><i class="dropdown-icon fe fe-edit-2"></i> Another action </a>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/client/show.blade.php
@extends('layouts.auth')
@section('content')

<div class="row">
    {{-- start profile client --}}
    <div class="col-4">
        <div class="card">
            <div class="card-body p-4 text-center">
                <span class="avatar avatar-xl mb-3 avatar-rounded"> J </span>
                <h3 class="m-0 mb-1"> {{$client->nama_client}} </a></h3>
                <div class="text-muted"> {{ $client->no_wa }} </div>
                <div class="mt-3">
                    <span class="badge bg-purple-lt">{{ $client->email }}</span>
                </div>
            </div>
            {{-- <div class="d-flex">
            <a href="#" class="card-btn">
                <!-- Download SVG icon from http://tabler-icons.io/i/mail -->
                <svg xmlns="http://www.w3.org/2000/svg" class="icon me-2 text-muted" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <rect x="3" y="5" width="18" height="14" rx="2" />
                    <polyline points="3 7 12 13 21 7" /></svg>
                Email</a>
            <a href="#" class="card-btn">
                <!-- Download SVG icon from http://tabler-icons.io/i/phone -->
                <svg xmlns="http://www.w3.org/2000/svg" class="icon me-2 text-muted" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <path d="M5 4h4l2 5l-2.5 1.5a11 11 0 0 0 5 5l1.5 -2.5l5 2v4a2 2 0 0 1 -2 2a16 16 0 0 1 -15 -15a2 2 0 0 1 2 -2" /></svg>
                Call</a>
        </div> --}}
        </div>
    </div>
    {{-- end profile client --}}


    <div class="col-8">
        {{-- start tabel project --}}
        <h3>Project</h3>
        <div class="card">
            <div class="table-responsive">
                <table class="table table-vcenter card-table">
                    <thead>
                        <tr>
                            <th>Nama Project</th>
                            <th>Harga</th>
                            <th>Nama Client</th>
                            <th>deadline</th>
                            <th class="w-1"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($projects as $project)
                        <tr>
                            <td>{{$project->nama_project}}</td>
                            <td class="text-muted">
                                {{$project->harga}}
                            </td>
                            <td class="text-muted"><a href="#" class="text-reset"> {{$project->client->nama_client}} </a></td>
                            <td class="text-muted">
                                {{$project->deadline}}
                            </td>
                            <td>
                                <div class="btn-list flex-nowrap">
                                    <div class="dropdown">
                                        <button class="btn dropdown-toggle align-text-top" data-bs-toggle="dropdown">
                                            Actions
                                        </button>
                                        <div class="dropdown-menu dropdown-menu-end">
                                            <form action="{{route('project.destroy', $project)}}" method="post">
                                                @csrf
                                                @method('delete')
                                                <button class="dropdown-item" type="submit">Hapus</button>
                                            </form>
                                            <form action="{{route('project.invoice', $project)}}" method="post">
                                                @csrf
                                                <button class="dropdown-item" type="submit"> Kirim </button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        {{-- end tabel project --}}

        {{-- start edit client --}}
        <div class="card mt-3">
            <form action="{{route('client.update', $client)}}" method="post">
                @csrf
                @method('put')
                <div class="modal-body">
                    <div class="mb-3">
                        <label class="form-label">Nama Client</label>
                        <input type="text" value="{{$client->nama_client}}" class="form-control" name="nama_client" placeholder="Nama Client">
                    </div>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="mb-3">
                                <label class="form-label">Nomor WA</label>
                                <input type="text" value="{{$client->no_wa}}" name="no_wa" placeholder="Nomor WA" class="form-control">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="mb-3">
                                <label class="form-label">Email</label>
                                <input type="email" value="{{$client->email}}" name="email" placeholder="E-mail" class="form-control">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary ms-auto">
                        Update Client
                    </button>
                </div>
            </form>
        </div>
        {{-- start edit client --}}

    </div>

</div>
@endsection